name = "VaraPress"
description = "A clean, fast, and responsive all-in-one Zola theme for Varavel projects"
tags = [
  "blog",
  "documentation",
  "docs",
  "landing",
  "responsive",
]
license = "MIT"
homepage = "https://github.com/varavelio/varapress"
min_version = "0.22.1" # Always same as in .devcontainer/Dockerfile
demo = "https://press.varavel.com"

[author]
name = "Varavel"
homepage = "https://varavel.com"

# Any variable there can be overridden in the end user `zola.toml`
[extra]
# Favicon shown in the browser tab.
varapress_favicon = "https://cdn.jsdelivr.net/gh/varavelio/brand@v1.0.2/dist/avatar-dark.svg"
# Logo shown in the docs header (light theme).
varapress_logo_light = "https://cdn.jsdelivr.net/gh/varavelio/brand@v1.0.2/dist/logo-black.svg"
# Logo shown in the docs header (dark theme).
varapress_logo_dark = "https://cdn.jsdelivr.net/gh/varavelio/brand@v1.0.2/dist/logo-white.svg"
# Set to false to hide the text title and only show the logo.
varapress_show_title = true
