title = "VaraPress"
description = "A clean, fast, and responsive all-in-one Zola theme for Varavel projects"
base_url = "https://press.varavel.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Customize the code highlighting
[markdown.highlighting]
theme = "github-dark"
extra_grammars = ["grammars/vdl.json"]
